USE [Endava_1stHomework]
GO

/****** Object:  Table [dbo].[OSIGURUVANJE]    Script Date: 12-Mar-23 7:04:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OSIGURUVANJE](
	[VRABOTEN_ID] [int] NOT NULL,
	[DATUM] [date] NULL,
	[OSIGURUVANJE] [varchar](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[VRABOTEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

