USE [master]
GO

/****** Object:  Database [Endava_1stHomework]    Script Date: 12-Mar-23 7:01:19 PM ******/
CREATE DATABASE [Endava_1stHomework]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Endava_1stHomework', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Endava_1stHomework.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Endava_1stHomework_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Endava_1stHomework_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Endava_1stHomework].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Endava_1stHomework] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET ARITHABORT OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Endava_1stHomework] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Endava_1stHomework] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Endava_1stHomework] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Endava_1stHomework] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET RECOVERY FULL 
GO

ALTER DATABASE [Endava_1stHomework] SET  MULTI_USER 
GO

ALTER DATABASE [Endava_1stHomework] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Endava_1stHomework] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Endava_1stHomework] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Endava_1stHomework] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Endava_1stHomework] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Endava_1stHomework] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Endava_1stHomework] SET QUERY_STORE = ON
GO

ALTER DATABASE [Endava_1stHomework] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Endava_1stHomework] SET  READ_WRITE 
GO

