USE [Endava_1stHomework]
GO

/****** Object:  Table [dbo].[VRABOTENI_PLATA]    Script Date: 12-Mar-23 7:05:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VRABOTENI_PLATA](
	[VRABOTEN_ID] [int] NOT NULL,
	[RABOTNO_MESTO] [varchar](50) NULL,
	[PLATA] [int] NULL,
 CONSTRAINT [PK_VRABOTENI_PLATA] PRIMARY KEY CLUSTERED 
(
	[VRABOTEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VRABOTENI_PLATA]  WITH CHECK ADD  CONSTRAINT [FK_VRABOTENI_PLATA_OSIGURUVANJE] FOREIGN KEY([PLATA])
REFERENCES [dbo].[OSIGURUVANJE] ([VRABOTEN_ID])
GO

ALTER TABLE [dbo].[VRABOTENI_PLATA] CHECK CONSTRAINT [FK_VRABOTENI_PLATA_OSIGURUVANJE]
GO

ALTER TABLE [dbo].[VRABOTENI_PLATA]  WITH CHECK ADD  CONSTRAINT [FK_VRABOTENI_PLATA_VRABOTENI] FOREIGN KEY([VRABOTEN_ID])
REFERENCES [dbo].[VRABOTENI] ([VRABOTEN_ID])
GO

ALTER TABLE [dbo].[VRABOTENI_PLATA] CHECK CONSTRAINT [FK_VRABOTENI_PLATA_VRABOTENI]
GO

